using System.Text;
using System.Text.Json;
using Erkan.Blazor.Chartjs.Tests.Infrastructure;

namespace Erkan.Blazor.Chartjs.Tests;

/// <summary>
/// Every key the models can emit must be a key Chart.js actually reads, at the nesting level
/// it reads it.
/// </summary>
/// <remarks>
/// <para>
/// This is the check the audit was really asking for. A C# property that serializes to
/// <c>"Text"</c>, to <c>y2AxisID</c>, to a Chart.js 1.x name, or to the right name one level
/// too high is invisible everywhere else: it compiles, it serializes, it reaches the browser,
/// and Chart.js silently ignores it. Six shipped defects had exactly that shape.
/// </para>
/// <para>
/// <b>Source of truth.</b> <c>ChartJs/chartjs-option-paths.json</c>, generated by
/// <c>tests/tools/chartjs-keys/generate.mjs</c> from the TypeScript declarations published by
/// Chart.js 4.5.1 and the bundled plugins, unioned with the live <c>defaults</c> of the
/// bundles vendored under <c>src/wwwroot/lib</c>. The generator refuses to run if the npm
/// versions it reads declarations from differ from the vendored bundle versions, so the two
/// can never describe different code. It is regenerated, not hand-edited, at every Chart.js
/// bump.
/// </para>
/// <para>
/// <b>What this catches.</b> A key Chart.js has no option for, anywhere; and a key that
/// exists but not under the parent the wrapper puts it under.
/// </para>
/// <para>
/// <b>What it does not catch.</b> Value types and shapes — a <c>string</c> where Chart.js
/// wants a number passes. Chart-type applicability: the eight types' option trees are unioned,
/// so a doughnut-only option set on a bar chart passes. Options a plugin reads dynamically
/// without declaring them. And it says nothing about whether an option that exists is wired
/// to anything useful.
/// </para>
/// </remarks>
public class ChartJsKeyValidationTests
{
    private static readonly ChartJsKeyList Keys = ChartJsKeyList.Current;

    /// <summary>
    /// Model types that are not part of a chart configuration: they carry data <em>from</em>
    /// JavaScript into .NET callbacks. Their shape is defined by the wrapper's own
    /// <c>src/wwwroot/Chart.js</c>, not by Chart.js's option tree, so validating them against
    /// Chart.js option paths would be meaningless.
    /// </summary>
    /// <remarks>
    /// The list is asserted to be exact, not merely sufficient: a new model type that no chart
    /// configuration can reach fails
    /// <see cref="Every_model_type_is_reachable_from_a_config_or_a_declared_inbound_payload"/>
    /// rather than quietly escaping validation.
    /// </remarks>
    private static readonly HashSet<string> InboundPayloadTypes =
    [
        "CallbackGenericContext",
        "ClickValue",
        "HoverContext",
        "LegendClickContext",
        "LegendFilterContext",
        "LegendItem",
        "TicksCallbackContext",
        "ZoomContext",
    ];

    /// <summary>
    /// Model types that carry <c>[JsonPropertyName]</c> but that no chart configuration can
    /// reach, so nothing they declare is ever serialized. Each one is dead weight on the public
    /// API rather than a serialization defect, and is reported as such.
    /// </summary>
    private static readonly HashSet<string> UnreachableModelTypes =
    [
        "Autocolors",
        "Colors",
        "LineDataType",
        "Parsing",
    ];

    // -----------------------------------------------------------------------------------

    /// <summary>
    /// The declared surface: every <c>[JsonPropertyName]</c> the model tree can reach, checked
    /// against Chart.js whether or not any fixture happens to set it.
    /// </summary>
    [Fact]
    public void Every_declared_key_lands_where_ChartJs_reads_it()
    {
        var offenders = ModelGraph.AllKeys
            .Where(key => !Keys.IsStripped(key.Path))
            .Where(key => !Keys.Paths.Contains(key.Path))
            .ToList();

        if (offenders.Count == 0) return;

        var report = new StringBuilder()
            .AppendLine($"{offenders.Count} serialized key(s) do not exist in Chart.js "
                        + $"{Keys.Versions.GetValueOrDefault("chart.js")} at the path the models write them to.")
            .AppendLine("Chart.js ignores an unknown key silently, so each of these is a property that")
            .AppendLine("compiles, serializes, reaches the browser and then does nothing.")
            .AppendLine();

        foreach (var key in offenders)
        {
            var parent = key.Path.Contains('.') ? key.Path[..key.Path.LastIndexOf('.')] : "";
            var siblings = Keys.Paths.ChildrenOf(parent);
            report.AppendLine($"  {key.Path}");
            report.AppendLine($"      written by  {key.Owner}");
            report.AppendLine(siblings.Count == 0
                ? $"      Chart.js has no option object at '{parent}' at all."
                : $"      '{parent}' accepts: {string.Join(", ", siblings.Take(24))}"
                  + (siblings.Count > 24 ? $", … ({siblings.Count} total)" : ""));
        }

        Assert.Fail(report.ToString());
    }

    /// <summary>
    /// The emitted surface. Complements the declared surface above: a custom
    /// <c>JsonConverter</c> can write keys no property declares — <c>ScaleLimits</c> does —
    /// and dictionary keys chosen at runtime only appear here.
    /// </summary>
    [Theory]
    [MemberData(nameof(EveryFixture))]
    public void Every_emitted_key_lands_where_ChartJs_reads_it(string fixture, string kind, string shape)
    {
        var config = Build(kind, shape);
        var offenders = JsonPaths.Enumerate(config)
            .Select(node => node.Path)
            .Distinct(StringComparer.Ordinal)
            .Where(path => !Keys.IsStripped(path))
            .Where(path => !Keys.Paths.Contains(path))
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(offenders.Count == 0,
            $"{fixture} serializes {offenders.Count} key(s) Chart.js does not read:{Environment.NewLine}  "
            + string.Join($"{Environment.NewLine}  ", offenders));
    }

    /// <summary>
    /// <c>LegendItem</c> travels the other way — Chart.js builds it and the wrapper deserializes
    /// it — so its members are validated against Chart.js's own <c>LegendItem</c> type.
    /// </summary>
    [Fact]
    public void LegendItem_members_exist_on_the_ChartJs_LegendItem()
    {
        var legendItem = ModelGraph.LibraryAssembly.GetType("Erkan.Blazor.Chartjs.Models.Common.LegendItem");
        Assert.NotNull(legendItem);

        var known = Keys.LegendItemPaths.ToHashSet(StringComparer.Ordinal);
        var offenders = ModelGraph.SerializedProperties(legendItem)
            .Select(ModelGraph.JsonKeyOf)
            .Where(key => !known.Contains(key))
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(offenders.Count == 0,
            $"LegendItem declares {offenders.Count} member(s) Chart.js's LegendItem does not have: "
            + $"{string.Join(", ", offenders)}. Chart.js sends: {string.Join(", ", Keys.LegendItemPaths)}");
    }

    /// <summary>
    /// Guards the escape hatch. Every model type is either reachable from a chart configuration
    /// — and therefore validated above — or explicitly declared as something else. A new type
    /// cannot slip into the unvalidated bucket by accident.
    /// </summary>
    [Fact]
    public void Every_model_type_is_reachable_from_a_config_or_a_declared_inbound_payload()
    {
        var reachable = ModelGraph.ReachableTypes.Select(t => t.Name).ToHashSet(StringComparer.Ordinal);

        var unaccounted = ModelGraph.TypesWithJsonPropertyNames()
            .Select(t => t.Name)
            .Where(name => !reachable.Contains(name))
            .Where(name => !InboundPayloadTypes.Contains(name))
            .Where(name => !UnreachableModelTypes.Contains(name))
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.True(unaccounted.Count == 0,
            $"{unaccounted.Count} model type(s) declare [JsonPropertyName] but no chart configuration "
            + $"can reach them, and they are not declared as inbound payloads: {string.Join(", ", unaccounted)}. "
            + "Either wire the type into a configuration, or add it to InboundPayloadTypes or "
            + "UnreachableModelTypes with a reason.");

        // and the declared-unreachable list must stay honest in the other direction too
        var nowReachable = UnreachableModelTypes.Where(reachable.Contains).Order(StringComparer.Ordinal).ToList();
        Assert.True(nowReachable.Count == 0,
            $"{string.Join(", ", nowReachable)} is listed as unreachable but a chart configuration now "
            + "reaches it. Remove it from UnreachableModelTypes so its keys get validated.");
    }

    /// <summary>
    /// The generated key list must describe the bundles this repository ships. Without this the
    /// whole check could be validating against a different Chart.js than the one users load.
    /// </summary>
    [Fact]
    public void The_key_list_describes_the_libraries_vendored_in_this_repository()
    {
        var libraries = Path.Combine(TestPaths.RepositoryRoot, "src", "wwwroot", "lib");

        var expected = new Dictionary<string, string>
        {
            ["chart.js"] = Path.Combine(libraries, "Chart.js", "chart.umd.js"),
            ["chartjs-plugin-zoom"] = Path.Combine(libraries, "chartjs-plugin-zoom", "chartjs-plugin-zoom.js"),
            ["chartjs-plugin-datalabels"] = Path.Combine(libraries, "chartjs-plugin-datalabels", "chartjs-plugin-datalabels.js"),
            ["chartjs-plugin-annotation"] = Path.Combine(libraries, "chartjs-plugin-annotation", "chartjs-plugin-annotation.min.js"),
            ["chartjs-plugin-autocolors"] = Path.Combine(libraries, "chartjs-plugin-autocolors", "chartjs-plugin-autocolors.min.js"),
        };

        foreach (var (package, bundle) in expected)
        {
            Assert.True(File.Exists(bundle), $"vendored bundle missing: {bundle}");

            var banner = File.ReadAllText(bundle)[..2000];
            var match = System.Text.RegularExpressions.Regex.Match(banner, @"v(\d+\.\d+\.\d+)");
            Assert.True(match.Success, $"no version banner in {bundle}");

            Assert.True(Keys.Versions.TryGetValue(package, out var recorded),
                $"the key list records no version for {package}");
            Assert.True(match.Groups[1].Value == recorded,
                $"{package} is vendored at {match.Groups[1].Value} but the Chart.js key list was generated "
                + $"against {recorded}. Regenerate it: cd tests/tools/chartjs-keys && npm install && npm run generate");
        }
    }

    /// <summary>
    /// The marker exemptions are derived from the interop module's own <c>delete</c> statements
    /// rather than hardcoded, so a marker added to the models without a matching delete is not
    /// exempt and fails the key check. This pins the derivation itself.
    /// </summary>
    [Fact]
    public void Marker_exemptions_are_the_keys_the_interop_module_deletes()
    {
        var interop = File.ReadAllText(TestPaths.InteropModule);

        foreach (var key in Keys.StrippedByInterop)
        {
            Assert.True(interop.Contains($".{key};", StringComparison.Ordinal)
                        || interop.Contains($".{key}\n", StringComparison.Ordinal),
                $"'{key}' is exempted from the Chart.js key check but src/wwwroot/Chart.js no longer "
                + "mentions it. Regenerate the key list.");
        }

        // the five markers the 2.0.0 notes call out, plus the three leaked option keys
        string[] required =
        [
            "hasFilter", "hasLabel", "hasCustomTitle", "hasCallback", "hasAsyncCallback",
            "crosshair", "groupXAxis", "groupYAxis",
        ];
        foreach (var key in required)
        {
            Assert.Contains(key, Keys.StrippedByInterop);
        }
    }

    // -----------------------------------------------------------------------------------

    private static object Build(string kind, string shape) => shape switch
    {
        "empty" => SampleConfigs.Empty(kind),
        "minimal" => SampleConfigs.Minimal(kind),
        "rich" => SampleConfigs.Rich(kind),
        _ => throw new ArgumentOutOfRangeException(nameof(shape), shape, null),
    };

    public static TheoryData<string, string, string> EveryFixture()
    {
        var data = new TheoryData<string, string, string>();
        foreach (var kind in SampleConfigs.Kinds)
        foreach (var shape in new[] { "empty", "minimal", "rich" })
            data.Add($"{kind}.{shape}", kind, shape);
        return data;
    }
}
